// <auto-generated />
using System;
using ApiEjemplo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEjemplo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417192339_AddClienteGeoFields")]
    partial class AddClienteGeoFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiEjemplo.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.Property<int>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cliente_id"));

                    b.Property<string>("colonia")
                        .HasColumnType("longtext");

                    b.Property<string>("curp")
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("latitud")
                        .HasColumnType("double");

                    b.Property<double?>("longitud")
                        .HasColumnType("double");

                    b.Property<string>("rfc")
                        .HasColumnType("longtext");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("cliente_id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("documento_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_original");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int")
                        .HasColumnName("prestamo_id");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ruta_archivo");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_mime");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("DocumentoId");

                    b.ToTable("documento");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Pago", b =>
                {
                    b.Property<int>("pago_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("pago_id"));

                    b.Property<int?>("cobrador_id")
                        .HasColumnType("int");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("APLICADO");

                    b.Property<DateTime>("fecha_pago")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("interes_pagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("metodo_pago")
                        .HasColumnType("longtext");

                    b.Property<decimal>("monto_pagado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("mora_pagada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("prestamo_id")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo_restante")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("pago_id");

                    b.HasIndex("prestamo_id");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.Property<int>("prestamo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("prestamo_id"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<int?>("cobrador_id")
                        .HasColumnType("int");

                    b.Property<int>("dias_gracia")
                        .HasColumnType("int");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_proximo_pago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("forma_pago")
                        .HasColumnType("int");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("monto_total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("mora_diaria")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("pago_mes")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("plazo_meses")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo_actual")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("tasa_interes")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("prestamo_id");

                    b.HasIndex("cliente_id");

                    b.HasIndex("cobrador_id");

                    b.ToTable("prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refresh_token_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Usuario", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .HasColumnType("longtext");

                    b.HasKey("usuario_id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("ApiEjemplo.Models.Cliente", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Pago", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Prestamo", "Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("prestamo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEjemplo.Models.Usuario", "Cobrador")
                        .WithMany()
                        .HasForeignKey("cobrador_id");

                    b.Navigation("Cliente");

                    b.Navigation("Cobrador");
                });

            modelBuilder.Entity("ApiEjemplo.Models.RefreshToken", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
