// <auto-generated />
using System;
using ApiEjemplo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEjemplo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517072308_AddPeriodoAmortizacion")]
    partial class AddPeriodoAmortizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiEjemplo.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.Property<int>("cliente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("cliente_id"));

                    b.Property<string>("apellido_materno")
                        .HasColumnType("longtext");

                    b.Property<string>("clave_cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("colonia")
                        .HasColumnType("longtext");

                    b.Property<string>("curp")
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_correo")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_rfc")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_telefono_celular")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_telefono_oficina")
                        .HasColumnType("longtext");

                    b.Property<string>("empresa_telefono_particular")
                        .HasColumnType("longtext");

                    b.Property<string>("estado_civil")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("latitud")
                        .HasColumnType("double");

                    b.Property<double?>("longitud")
                        .HasColumnType("double");

                    b.Property<string>("lugar_nacimiento")
                        .HasColumnType("longtext");

                    b.Property<int?>("no_dependientes")
                        .HasColumnType("int");

                    b.Property<bool>("permitir_acceso_web")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("rfc")
                        .HasColumnType("longtext");

                    b.Property<string>("ruta_vinculacion")
                        .HasColumnType("longtext");

                    b.Property<string>("sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("telefono_oficina")
                        .HasColumnType("longtext");

                    b.Property<string>("telefono_particular")
                        .HasColumnType("longtext");

                    b.Property<string>("tipo_cliente")
                        .HasColumnType("longtext");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("cliente_id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("documento_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_original");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int")
                        .HasColumnName("prestamo_id");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ruta_archivo");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_mime");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("DocumentoId");

                    b.ToTable("documento");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Gerencia", b =>
                {
                    b.Property<int>("gerencia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("gerencia_id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("es_principal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("gerente_id")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("gerencia_id");

                    b.HasIndex("gerente_id");

                    b.ToTable("gerencia");
                });

            modelBuilder.Entity("ApiEjemplo.Models.GestionCobranza", b =>
                {
                    b.Property<int>("gestion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("gestion_id"));

                    b.Property<DateTime>("fecha_gestion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prestamo_id")
                        .HasColumnType("int");

                    b.Property<string>("redaccion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("gestion_id");

                    b.HasIndex("prestamo_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("gestion_cobranza");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Grupo", b =>
                {
                    b.Property<int>("grupo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("grupo_id"));

                    b.Property<string>("clasificacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("destino")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("forma_pago")
                        .HasColumnType("int");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("moratorio_por_dia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("plazo_meses")
                        .HasColumnType("int");

                    b.Property<decimal>("tasa_interes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("tb_interes_moratorio")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tb_interes_normal")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tipo_cnbv")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo_tasa")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tipo_tasa_moratorio")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("grupo_id");

                    b.ToTable("grupo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.NotificacionAgendada", b =>
                {
                    b.Property<int>("notificacion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("notificacion_id"));

                    b.Property<string>("detalles")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("fecha_hora")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("prestamo_id")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("notificacion_id");

                    b.HasIndex("prestamo_id");

                    b.ToTable("notificacion_agendada");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Pago", b =>
                {
                    b.Property<int>("pago_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("pago_id"));

                    b.Property<int?>("cobrador_id")
                        .HasColumnType("int");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("APLICADO");

                    b.Property<DateTime>("fecha_pago")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("interes_pagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("metodo_pago")
                        .HasColumnType("longtext");

                    b.Property<decimal>("monto_pagado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("mora_pagada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("prestamo_id")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo_restante")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("pago_id");

                    b.HasIndex("prestamo_id");

                    b.ToTable("pago");
                });

            modelBuilder.Entity("ApiEjemplo.Models.PeriodoAmortizacion", b =>
                {
                    b.Property<int>("periodo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("periodo_id"));

                    b.Property<decimal>("abono_capital")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("ahorro_por_pago")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("capital_pendiente")
                        .HasColumnType("decimal(16,4)");

                    b.Property<int>("dias_moratorio")
                        .HasColumnType("int");

                    b.Property<int>("estado_pago")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_pagado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_vencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("gasto_cobranza")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("interes_iva")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("interes_moratorio")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("interes_normal")
                        .HasColumnType("decimal(16,4)");

                    b.Property<decimal>("pago_pactado")
                        .HasColumnType("decimal(16,4)");

                    b.Property<int>("periodo")
                        .HasColumnType("int");

                    b.Property<int>("prestamo_id")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo_final")
                        .HasColumnType("decimal(16,4)");

                    b.HasKey("periodo_id");

                    b.HasIndex("prestamo_id");

                    b.ToTable("periodo_amortizacion");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.Property<int>("prestamo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("prestamo_id"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<int?>("cobrador_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("comision_apertura")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("destino")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("dias_gracia")
                        .HasColumnType("int");

                    b.Property<string>("estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_proximo_pago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("forma_pago")
                        .HasColumnType("int");

                    b.Property<decimal?>("g_alimento")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_creditos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_inversion")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_luz")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_otros")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_renta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_telefono")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("g_transporte")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("grupo_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("ing_otros")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ing_semanal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ing_total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("iva")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("monto_total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("mora_diaria")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("nombre_banco")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("num_cuenta")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("pago_mes")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("plazo_meses")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo_actual")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("seguro_credito")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("tasa_interes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("tasa_moratorio_anual")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("tb_interes_moratorio")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tb_interes_normal")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tipo_cnbv")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo_tasa")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("tipo_tasa_moratorio")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("total_disponible")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("total_gasto")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("prestamo_id");

                    b.HasIndex("cliente_id");

                    b.HasIndex("cobrador_id");

                    b.HasIndex("grupo_id");

                    b.ToTable("prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refresh_token_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Ruta", b =>
                {
                    b.Property<int>("ruta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ruta_id"));

                    b.Property<int?>("asesor_id")
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("gerencia_id")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ruta_id");

                    b.HasIndex("asesor_id");

                    b.HasIndex("gerencia_id");

                    b.ToTable("ruta");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Usuario", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("usuario_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .HasColumnType("longtext");

                    b.HasKey("usuario_id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("ApiEjemplo.Models.Cliente", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Gerencia", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Gerente")
                        .WithMany()
                        .HasForeignKey("gerente_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gerente");
                });

            modelBuilder.Entity("ApiEjemplo.Models.GestionCobranza", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("prestamo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEjemplo.Models.Usuario", "Gestor")
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gestor");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.NotificacionAgendada", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("prestamo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Pago", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Prestamo", "Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("prestamo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.PeriodoAmortizacion", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("prestamo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiEjemplo.Models.Usuario", "Cobrador")
                        .WithMany()
                        .HasForeignKey("cobrador_id");

                    b.HasOne("ApiEjemplo.Models.Grupo", "Grupo")
                        .WithMany("Prestamos")
                        .HasForeignKey("grupo_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Cobrador");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ApiEjemplo.Models.RefreshToken", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Ruta", b =>
                {
                    b.HasOne("ApiEjemplo.Models.Usuario", "Asesor")
                        .WithMany()
                        .HasForeignKey("asesor_id");

                    b.HasOne("ApiEjemplo.Models.Gerencia", "Gerencia")
                        .WithMany("Rutas")
                        .HasForeignKey("gerencia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asesor");

                    b.Navigation("Gerencia");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Gerencia", b =>
                {
                    b.Navigation("Rutas");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Grupo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("ApiEjemplo.Models.Prestamo", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
